wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: eval-rmse
      6:
      - 3
      7:
      - 1
    - 1: train-rmse
      6:
      - 3
      7:
      - 1
    python_version: 3.10.4
    start_time: 1654011571
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      3:
      - 7
      - 16
      - 31
      4: 3.10.4
      5: 0.12.17
      8:
      - 1
      - 5
    visualize:
      Feature Importance:
        panel_config:
          fieldSettings:
            label: Feature
            value: Importance
          panelDefId: wandb/bar/v0
          stringSettings:
            title: Feature Importance
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Feature Importance_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
eta:
  desc: null
  value: 0.01
gamma:
  desc: null
  value: 0
grow_policy:
  desc: null
  value: lossguide
l1:
  desc: null
  value: 0
l2:
  desc: null
  value: 1
learner:
  desc: null
  value:
    generic_param:
      fail_on_invalid_gpu_id: '0'
      gpu_id: '-1'
      n_jobs: '12'
      nthread: '12'
      random_state: '0'
      seed: '0'
      seed_per_iteration: '0'
      validate_parameters: '1'
    gradient_booster:
      gbtree_train_param:
        num_parallel_tree: '1'
        predictor: auto
        process_type: default
        tree_method: hist
        updater: grow_quantile_histmaker
        updater_seq: grow_quantile_histmaker
      name: gbtree
      specified_updater: false
      updater:
        grow_quantile_histmaker:
          cpu_hist_train_param:
            single_precision_histogram: '0'
          train_param:
            alpha: '0'
            cache_opt: '1'
            colsample_bylevel: '1'
            colsample_bynode: '1'
            colsample_bytree: '1'
            default_direction: learn
            eta: '0.00999999978'
            gamma: '0'
            grow_policy: lossguide
            interaction_constraints: ''
            lambda: '1'
            learning_rate: '0.00999999978'
            max_bin: '10000'
            max_conflict_rate: '0'
            max_delta_step: '0'
            max_depth: '0'
            max_leaves: '6'
            max_search_group: '100'
            min_child_weight: '1'
            min_split_loss: '0'
            monotone_constraints: ()
            refresh_leaf: '1'
            reg_alpha: '0'
            reg_lambda: '1'
            sampling_method: uniform
            sketch_eps: '0.0299999993'
            sketch_ratio: '2'
            sparse_threshold: '0.20000000000000001'
            split_evaluator: elastic_net,monotonic
            subsample: '1'
    learner_model_param:
      base_score: 5E-1
      num_class: '0'
      num_feature: '4'
    learner_train_param:
      booster: gbtree
      disable_default_eval_metric: '0'
      dsplit: auto
      objective: reg:squarederror
    metrics: []
    objective:
      name: reg:squarederror
      reg_loss_param:
        scale_pos_weight: '1'
max_bin:
  desc: null
  value: 10000
max_depth:
  desc: null
  value: 0
max_leaves:
  desc: null
  value: 6
mds:
  desc: null
  value: 0
objective:
  desc: null
  value: reg:squarederror
tree_method:
  desc: null
  value: hist
version:
  desc: null
  value:
  - 1
  - 5
  - 1
