wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1654011414
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 16
      - 31
      4: 3.10.4
      5: 0.12.17
      8:
      - 1
      - 5
eta:
  desc: null
  value: 0.01
gamma:
  desc: null
  value: 0
grow_policy:
  desc: null
  value: lossguide
l1:
  desc: null
  value: 0
l2:
  desc: null
  value: 1
max_bin:
  desc: null
  value: 10000
max_depth:
  desc: null
  value: 0
max_leaves:
  desc: null
  value: 6
mds:
  desc: null
  value: 0
objective:
  desc: null
  value: reg:squarederror
tree_method:
  desc: null
  value: gpu_hist
